import type { AreaDefinition, FishDefinition, ItemDefinition, QuestDefinition } from "./types";

export const fish: FishDefinition[] = [
  {
    id: "sunny-minnow",
    name: "햇살 송사리",
    areaIds: ["sunny-beach"],
    rarity: "common",
    baseShells: 8,
    xp: 8,
    spawnWeight: 38,
    funFact: "햇빛이 비치면 비늘이 반짝여요.",
    assetKey: "fish-sunny-minnow",
  },
  {
    id: "bubble-flounder",
    name: "방울 가자미",
    areaIds: ["sunny-beach"],
    rarity: "common",
    baseShells: 10,
    xp: 9,
    spawnWeight: 30,
    funFact: "모래 위에서 숨바꼭질을 잘해요.",
    assetKey: "fish-bubble-flounder",
  },
  {
    id: "sand-shrimp",
    name: "모래 새우",
    areaIds: ["sunny-beach"],
    rarity: "common",
    baseShells: 9,
    xp: 8,
    spawnWeight: 28,
    funFact: "꼬리를 톡톡 튕기며 모래 위를 날아다녀요.",
    assetKey: "fish-sand-shrimp",
  },
  {
    id: "peach-seahorse",
    name: "복숭아 해마",
    areaIds: ["sunny-beach"],
    rarity: "uncommon",
    baseShells: 18,
    xp: 15,
    spawnWeight: 15,
    funFact: "작은 산호잎을 붙잡고 살랑살랑 춤춰요.",
    assetKey: "fish-peach-seahorse",
  },
  {
    id: "ribbon-squid",
    name: "리본 오징어",
    areaIds: ["sunny-beach", "little-pier"],
    rarity: "uncommon",
    baseShells: 16,
    xp: 14,
    spawnWeight: 18,
    funFact: "팔을 흔들며 인사하는 걸 좋아해요.",
    assetKey: "fish-ribbon-squid",
  },
  {
    id: "moon-jelly",
    name: "달빛 해파리",
    areaIds: ["sunny-beach", "little-pier"],
    rarity: "uncommon",
    baseShells: 19,
    xp: 16,
    spawnWeight: 14,
    funFact: "밤바다에서는 작은 달처럼 은은하게 빛나요.",
    assetKey: "fish-moon-jelly",
  },
  {
    id: "harbor-mackerel",
    name: "항구 고등어",
    areaIds: ["little-pier"],
    rarity: "common",
    baseShells: 14,
    xp: 12,
    spawnWeight: 35,
    funFact: "항구의 물결을 따라 빠르게 헤엄쳐요.",
    assetKey: "fish-harbor-mackerel",
  },
  {
    id: "shell-crab",
    name: "조개 게",
    areaIds: ["little-pier"],
    rarity: "uncommon",
    baseShells: 20,
    xp: 17,
    spawnWeight: 22,
    funFact: "작은 조개껍데기를 모자처럼 쓰고 다녀요.",
    assetKey: "fish-shell-crab",
  },
  {
    id: "drum-octopus",
    name: "북치는 문어",
    areaIds: ["little-pier"],
    rarity: "uncommon",
    baseShells: 23,
    xp: 19,
    spawnWeight: 18,
    funFact: "다리로 통통 리듬을 만들며 친구들을 불러요.",
    assetKey: "fish-drum-octopus",
  },
  {
    id: "sleepy-ray",
    name: "꾸벅 가오리",
    areaIds: ["little-pier"],
    rarity: "rare",
    baseShells: 36,
    xp: 28,
    spawnWeight: 8,
    funFact: "넓은 지느러미로 이불처럼 바다 모래를 덮어요.",
    assetKey: "fish-sleepy-ray",
  },
  {
    id: "candy-puffer",
    name: "사탕 복어",
    areaIds: ["little-pier", "coral-sea"],
    rarity: "uncommon",
    baseShells: 27,
    xp: 22,
    spawnWeight: 16,
    funFact: "놀라면 동그랗게 부풀어 사탕처럼 보여요.",
    assetKey: "fish-candy-puffer",
  },
  {
    id: "starfish-pal",
    name: "별친구 불가사리",
    areaIds: ["little-pier", "coral-sea"],
    rarity: "rare",
    baseShells: 32,
    xp: 26,
    spawnWeight: 9,
    funFact: "밤이 되면 별처럼 반짝이는 친구예요.",
    assetKey: "fish-starfish-pal",
  },
  {
    id: "coral-tang",
    name: "산호 탱글이",
    areaIds: ["coral-sea"],
    rarity: "common",
    baseShells: 22,
    xp: 18,
    spawnWeight: 32,
    funFact: "산호 사이를 통통 튀듯 움직여요.",
    assetKey: "fish-coral-tang",
  },
  {
    id: "ribbon-eel",
    name: "리본 장어",
    areaIds: ["coral-sea"],
    rarity: "common",
    baseShells: 24,
    xp: 20,
    spawnWeight: 24,
    funFact: "긴 몸으로 파도 무늬를 그리며 헤엄쳐요.",
    assetKey: "fish-ribbon-eel",
  },
  {
    id: "pearl-clam",
    name: "진주 조개",
    areaIds: ["coral-sea"],
    rarity: "rare",
    baseShells: 46,
    xp: 35,
    spawnWeight: 10,
    funFact: "기분이 좋으면 조개껍데기 사이로 빛을 내요.",
    assetKey: "fish-pearl-clam",
  },
  {
    id: "pearl-turtle",
    name: "진주 거북",
    areaIds: ["coral-sea"],
    rarity: "rare",
    baseShells: 44,
    xp: 34,
    spawnWeight: 12,
    funFact: "등껍질에 작은 진주빛 무늬가 있어요.",
    assetKey: "fish-pearl-turtle",
  },
  {
    id: "lantern-angler",
    name: "초롱 아귀",
    areaIds: ["coral-sea"],
    rarity: "rare",
    baseShells: 50,
    xp: 38,
    spawnWeight: 7,
    funFact: "머리 위 초롱불로 어두운 산호길을 밝혀요.",
    assetKey: "fish-lantern-angler",
  },
  {
    id: "sea-bunny",
    name: "바다 토끼",
    areaIds: ["coral-sea"],
    rarity: "special",
    baseShells: 72,
    xp: 54,
    spawnWeight: 4,
    funFact: "토끼 귀 같은 더듬이로 반짝 소리를 들어요.",
    assetKey: "fish-sea-bunny",
  },
  {
    id: "rainbow-whale",
    name: "무지개 아기고래",
    areaIds: ["coral-sea"],
    rarity: "special",
    baseShells: 80,
    xp: 60,
    spawnWeight: 3,
    funFact: "아주 특별한 날, 바다 위에 무지개 물방울을 만들어요.",
    assetKey: "fish-rainbow-whale",
  },
];

export const areas: AreaDefinition[] = [
  {
    id: "sunny-beach",
    name: "햇살 해변",
    requiredLevel: 1,
    fishIds: ["sunny-minnow", "bubble-flounder", "sand-shrimp", "peach-seahorse", "ribbon-squid", "moon-jelly"],
    backgroundKey: "bg-sunny-beach",
  },
  {
    id: "little-pier",
    name: "작은 방파제",
    requiredLevel: 3,
    fishIds: [
      "ribbon-squid",
      "moon-jelly",
      "harbor-mackerel",
      "shell-crab",
      "drum-octopus",
      "sleepy-ray",
      "candy-puffer",
      "starfish-pal",
    ],
    backgroundKey: "bg-little-pier",
  },
  {
    id: "coral-sea",
    name: "산호초 바다",
    requiredLevel: 5,
    fishIds: [
      "starfish-pal",
      "candy-puffer",
      "coral-tang",
      "ribbon-eel",
      "pearl-clam",
      "pearl-turtle",
      "lantern-angler",
      "sea-bunny",
      "rainbow-whale",
    ],
    backgroundKey: "bg-coral-sea",
  },
];

export const items: ItemDefinition[] = [
  {
    id: "twig-rod",
    name: "나뭇가지 낚싯대",
    kind: "rod",
    shellCost: 0,
    description: "처음부터 함께하는 든든한 낚싯대예요.",
    effect: { catchEase: 0 },
  },
  {
    id: "sparkle-rod",
    name: "반짝 낚싯대",
    kind: "rod",
    shellCost: 70,
    description: "타이밍 구간이 조금 넓어져요.",
    effect: { catchEase: 0.08 },
  },
  {
    id: "captain-rod",
    name: "용감한 선장 낚싯대",
    kind: "rod",
    shellCost: 150,
    description: "큰 친구를 만날 때 마음이 더 편해져요.",
    effect: { catchEase: 0.13 },
  },
  {
    id: "sweet-bait",
    name: "달콤 미끼",
    kind: "bait",
    shellCost: 45,
    description: "가끔 만나는 친구가 조금 더 찾아와요.",
    effect: { rareBoost: 0.18 },
  },
  {
    id: "coral-bait",
    name: "산호 미끼",
    kind: "bait",
    shellCost: 90,
    description: "특별한 바다 친구를 만날 확률이 올라가요.",
    effect: { rareBoost: 0.32 },
  },
  {
    id: "star-flag",
    name: "별 깃발",
    kind: "boatCosmetic",
    shellCost: 60,
    description: "배 위에서 살랑살랑 빛나는 깃발이에요.",
  },
];

export const quests: QuestDefinition[] = [
  {
    id: "first-friend",
    title: "첫 바다 친구 만나기",
    helper: "낚시 버튼을 눌러 첫 친구를 만나봐요.",
    steps: [{ kind: "catchAny", count: 1 }],
    rewards: { shells: 25, xp: 18 },
  },
  {
    id: "tiny-collector",
    title: "도감에 친구 3종 기록하기",
    helper: "서로 다른 바다 친구를 세 종류 만나봐요.",
    steps: [{ kind: "collectUnique", count: 3 }],
    rewards: { shells: 40, xp: 28 },
  },
  {
    id: "better-rod",
    title: "반짝 낚싯대 준비하기",
    helper: "조개를 모아 반짝 낚싯대를 바꿔봐요.",
    steps: [{ kind: "ownItem", itemId: "sparkle-rod" }],
    rewards: { shells: 30, xp: 30 },
  },
  {
    id: "pier-trip",
    title: "작은 방파제로 떠나요",
    helper: "레벨 3이 되면 새로운 낚시터가 열려요.",
    steps: [{ kind: "unlockArea", areaId: "little-pier" }],
    rewards: { shells: 45, xp: 35 },
  },
  {
    id: "rainbow-dream",
    title: "무지개 아기고래 소문",
    helper: "산호초 바다에서 특별한 친구를 찾아봐요.",
    steps: [
      { kind: "unlockArea", areaId: "coral-sea" },
      { kind: "catchFish", fishId: "rainbow-whale", count: 1 },
    ],
    rewards: { shells: 120, xp: 80, itemId: "star-flag" },
  },
];

export const getFish = (id: string) => fish.find((entry) => entry.id === id);
export const getArea = (id: string) => areas.find((entry) => entry.id === id);
export const getItem = (id: string) => items.find((entry) => entry.id === id);
export const getQuest = (id: string) => quests.find((entry) => entry.id === id);
